name: ebv
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  reactive_forms: ^17.0.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  sms_autofill: ^2.4.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  http: ^1.4.0
  fluttertoast: ^8.2.12
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.7
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  flutter_native_splash: ^2.4.4
  permission_handler: ^12.0.1
  audioplayers: ^6.5.0
  just_audio: ^0.10.4
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  syncfusion_flutter_pdfviewer: ^29.1.38
  syncfusion_flutter_calendar: ^29.1.38
  flutter_local_notifications: ^19.4.0
  syncfusion_flutter_charts: ^29.1.38
  fl_chart: ^0.71.0
  encrypt: ^5.0.3
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  iconsax: ^0.0.8
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_image_compress: ^2.4.0
  cryptography: 2.8.0
#  rsa_pkcs: 2.1.0
#  pointycastle: ^3.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

